apiVersion: apps/v1
kind: Deployment
metadata:
  name: oyalmli-deployment
  labels:
    app: oyalmli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oyalmli
  template:
    metadata:
      labels:
        app: oyalmli
    spec:
      containers:
      - name: oyalmli
        image: latest
        ports:
        - containerPort: 80