apiVersion: apps/v1
kind: Deployment
metadata:
  name: oyalmli
  namespace: apps
  labels:
    k8s-app: oyalmli
spec:
  replicas: 2
  selector:
    matchLabels:
      name: oyalmli
  template:
    metadata:
      labels:
        name: oyalmli
        k8s-app: oyalmli
    spec:
      containers:
      - name: oyalmli
        image: registry.digitalocean.com/olsen/oyalmli
  strategy:
    type: RollingUpdate
  minReadySeconds: 5
