kind: Deployment
apiVersion: apps/v1
metadata:
  name: oyalmli
  namespace: apps
  labels:
    k8s-app: oyalmli
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: oyalmli
  template:
    metadata:
      name: oyalmli
      labels:
        k8s-app: oyalmli
    spec:
      containers:
        - name: oyalmli
          image: registry.digitalocean.com/olsen/oyalmli
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
  minReadySeconds: 5