kind: Service
apiVersion: v1
metadata:
  name: oyalmli
  namespace: apps
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    k8s-app: oyalmli
  type: ClusterIP
  ipFamilyPolicy: SingleStack